plugins:
  check_credentials_api_key:
    default: ""
    client: false
    type: text

  check_credentials_allowed_ips:
    default: ""
    client: false
    type: text

  check_credentials_max_rate:
    default: 5
    client: false
    type: integer
